const { ProjectGenerator } = require("../models/ProjectGenerator");
const { ai, projectGeneratorConfig } = require("../config/gemini");
const { callAIWithFallback } = require('../utils/aiWithFallback');

// 1. Generate Project Blueprint
const generateProject = async (req, res) => {
  try {
    const { request } = req.body;

    if (!request) {
      return res.status(400).json({
        success: false,
        message: 'Please provide a project request (e.g. "Suggest a Node.js intermediate project")',
      });
    }

    const prompt = `
      User request: "${request}"

      If this request is asking for a project idea/suggestion, generate a full specification.
      If it is NOT asking for a project idea, return empty arrays/default strings and set description to:
      "I can only suggest and generate project ideas. Please ask me for a project suggestion."

      Respond STRICTLY in JSON matching this schema:
      {
        "projectTitle": "Title",
        "difficultyLevel": "Beginner | Intermediate | Advanced",
        "techStack": ["React", "Node.js"],
        "description": "Short project description",
        "features": ["User Authentication", "Car Listings", "Booking System", "Payment Gateway"],
        "folderStructure": [
          { "path": "src/controllers", "description": "Contains route handlers" }
        ],
        "databaseSchema": [
          {
            "modelName": "User",
            "fields": [
              { "fieldName": "email", "fieldType": "String", "description": "User email address" }
            ]
          }
        ]
      }
      CRITICAL: 'features' MUST be a simple flat array of strings, NOT an array of objects.
    `;

    const response = await callAIWithFallback(ai, projectGeneratorConfig, prompt);
    console.log(`Generated by: ${response.provider} on attempt: ${response.attempt}`);

    const cleanText = response.text.replace(/```json/g, '').replace(/```/g, '').trim();
    const parsed = JSON.parse(cleanText);

    let rawFeatures = parsed.features || [];
    let formattedFeatures = [];

    if (Array.isArray(rawFeatures)) {
      rawFeatures.forEach(item => {
        if (typeof item === 'string') {
          formattedFeatures.push(item);
        } else if (typeof item === 'object' && item !== null) {
          Object.values(item).forEach(val => {
            if (Array.isArray(val)) {
              formattedFeatures.push(...val.filter(v => typeof v === 'string'));
            } else if (typeof val === 'string') {
              formattedFeatures.push(val);
            }
          });
        }
      });
    }

    const projectGen = await ProjectGenerator.create({
      user: req.user._id,
      request,
      projectTitle: parsed.projectTitle || "Project Blueprint",
      difficultyLevel: parsed.difficultyLevel || "Intermediate",
      techStack: Array.isArray(parsed.techStack) ? parsed.techStack : [],
      description: parsed.description || "",
      features: formattedFeatures,
      folderStructure: Array.isArray(parsed.folderStructure) ? parsed.folderStructure : [],
      databaseSchema: Array.isArray(parsed.databaseSchema) ? parsed.databaseSchema : [],
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Project generated successfully",
      project: projectGen,
    });
  } catch (error) {
    if (error.message && error.message.includes("All 5 attempts failed")) {
      return res.status(429).json({
        success: false,
        message: "Service temporarily unavailable. Please try again later.",
      });
    }
    console.error("Generate project error:", error);
    res.status(500).json({
      success: false,
      message: "Server error generating project",
    });
  }
};

// 2. Get all projects for logged in user
const getProjects = async (req, res) => {
  try {
    const projects = await ProjectGenerator.find({ user: req.user._id })
      .select("-rawResponse")
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      count: projects.length,
      projects,
    });
  } catch (error) {
    console.error("Get projects error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching projects",
    });
  }
};

// 3. Get single project by ID
const getProject = async (req, res) => {
  try {
    const { id } = req.params;

    const project = await ProjectGenerator.findOne({
      _id: id,
      user: req.user._id,
    }).select("-rawResponse");

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    res.json({
      success: true,
      project,
    });
  } catch (error) {
    console.error("Get project error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching project",
    });
  }
};

// 4. Delete project by ID
const deleteProject = async (req, res) => {
  try {
    const { id } = req.params;

    const project = await ProjectGenerator.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    res.json({
      success: true,
      message: "Project deleted successfully",
    });
  } catch (error) {
    console.error("Delete project error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting project",
    });
  }
};

module.exports = { 
  generateProject, 
  getProjects, 
  getProject, 
  deleteProject 
};