const ProjectGenerator = require("../models/ProjectGenerator");
const { ai, projectGeneratorConfig } = require("../config/gemini");
const { callAIWithFallback } = require('../utils/aiWithFallback');

const generateProject = async (req, res) => {
  try {
    const { request } = req.body;

    if (!request) {
      return res.status(400).json({
        success: false,
        message:
          'Please provide a project request (e.g. "Suggest a Node.js intermediate project")',
      });
    }

    const prompt = `
      User request: "${request}"

      If this request is asking for a project idea/suggestion, generate:
      1. Project Title
      2. Difficulty Level
      3. Tech Stack
      4. Short Description
      5. Features (core to nice-to-have)
      6. Folder Structure (realistic, following conventions for the tech stack)
      7. Database Schema (models with fields and types)

      If this request is NOT asking for a project idea (e.g. it's a general question,
      a code snippet to review, or anything unrelated), respond in JSON with all fields
      empty/default and set "description" to:
      "I can only suggest and generate project ideas. Please ask me for a project suggestion (e.g. 'Suggest a Node.js intermediate project')."

      Response must be in JSON format following the exact schema provided.
    `;

    

    const response = await callAIWithFallback(ai, projectGeneratorConfig, prompt);
    console.log(
      `Generated by: ${response.provider} on attempt: ${response.attempt}`,
    );
    const parsedRoadmap = JSON.parse(response.text);

    const parsed = JSON.parse(response.text);

    const projectGen = await ProjectGenerator.create({
      user: req.user._id,
      request,
      projectTitle: parsed.projectTitle,
      difficultyLevel: parsed.difficultyLevel,
      techStack: parsed.techStack,
      description: parsed.description,
      features: parsed.features,
      folderStructure: parsed.folderStructure,
      databaseSchema: parsed.databaseSchema,
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Project generated successfully",
      project: projectGen,
    });
  } catch (error) {
    if (error.message.includes("All 5 attempts failed")) {
      return res.status(429).json({
        success: false,
        message: "Service temporarily unavailable. Please try again later.",
      });
    }
    console.error("Generate roadmap error:", error);
    res.status(500).json({
      success: false,
      message: "Server error generating roadmap",
    });
  }
};

// get all projects
const getProjects = async (req, res) => {
  try {
    const projects = await ProjectGenerator.find({ user: req.user._id })
      .select("-rawResponse")
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      count: projects.length,
      projects,
    });
  } catch (error) {
    console.error("Get projects error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching projects",
    });
  }
};

// get project by id
const getProject = async (req, res) => {
  try {
    const { id } = req.params;

    const project = await ProjectGenerator.findOne({
      _id: id,
      user: req.user._id,
    }).select("-rawResponse");

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    res.json({
      success: true,
      project,
    });
  } catch (error) {
    console.error("Get project error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching project",
    });
  }
};

// delete
const deleteProject = async (req, res) => {
  try {
    const { id } = req.params;

    const project = await ProjectGenerator.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!project) {
      return res.status(404).json({
        success: false,
        message: "Project not found",
      });
    }

    res.json({
      success: true,
      message: "Project deleted successfully",
    });
  } catch (error) {
    console.error("Delete project error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting project",
    });
  }
};

module.exports = { generateProject, getProjects, getProject, deleteProject };
