const Quiz = require("../models/Quiz");
const { ai, quizConfig } = require("../config/gemini");
const { callAIWithFallback } = require("../utils/aiWithFallback");

const generateQuiz = async (req, res) => {
  try {
    const { topic, difficulty, numberOfQuestions } = req.body;

    if (!topic) {
      return res.status(400).json({
        success: false,
        message: "Please provide a topic",
      });
    }

    // 1. Explicit prompt instructing Gemini to format options as a flat Array of 4 strings
    const prompt = `
      Generate ${numberOfQuestions || 10} MCQ questions about ${topic} at a ${difficulty || "beginner"} level.

      Return ONLY a valid JSON object matching this exact structure:
      {
        "quizTitle": "Title for the quiz",
        "questions": [
          {
            "question": "Question text here?",
            "options": ["First option", "Second option", "Third option", "Fourth option"],
            "correctAnswer": "A",
            "explanation": "Clear explanation of the correct answer."
          }
        ]
      }

      Rules:
      - "options" MUST be a JSON array containing exactly 4 string options.
      - Do NOT prefix options with letters like "A)" or "1.".
      - "correctAnswer" MUST be exactly one character: "A", "B", "C", or "D" (where A maps to option[0], B to option[1], etc.).
      - Return pure JSON only. Do not wrap in markdown or backticks.
    `;

    const response = await callAIWithFallback(ai, quizConfig, prompt);
    console.log(
      `Generated by: ${response.provider} on attempt: ${response.attempt}`
    );

    // 2. Strip potential markdown backticks before parsing JSON
    const cleanText = response.text
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .trim();

    const parsedQuiz = JSON.parse(cleanText);

    const quiz = await Quiz.create({
      user: req.user._id,
      topic,
      difficulty: difficulty || "beginner",
      numberOfQuestions: numberOfQuestions || 10,
      quizTitle: parsedQuiz.quizTitle,
      questions: parsedQuiz.questions,
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Quiz generated successfully",
      quiz,
    });
  } catch (error) {
    if (error.message && error.message.includes("All 5 attempts failed")) {
      return res.status(429).json({
        success: false,
        message: "Service temporarily unavailable. Please try again later.",
      });
    }
    console.error("Generate quiz error:", error);
    res.status(500).json({
      success: false,
      message: "Server error generating quiz",
    });
  }
};
// Submit Quiz Answers & Save Marks
const submitQuiz = async (req, res) => {
  try {
    const { id } = req.params;
    const { userAnswers } = req.body; // Expecting { "0": "A", "1": "C", ... }

    if (!userAnswers || typeof userAnswers !== "object") {
      return res.status(400).json({
        success: false,
        message: "Invalid or missing user answers",
      });
    }

    const quiz = await Quiz.findOne({
      _id: id,
      user: req.user._id,
    });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: "Quiz not found",
      });
    }

    // Evaluate score against complete stored questions array
    let score = 0;
    const totalMarks = quiz.questions.length;

    quiz.questions.forEach((question, index) => {
      // Look up answer by integer index or string key
      const selectedAnswer = userAnswers[index] ?? userAnswers[String(index)];
      if (selectedAnswer && selectedAnswer === question.correctAnswer) {
        score += 1;
      }
    });

    const percentage = totalMarks > 0 ? Math.round((score / totalMarks) * 100) : 0;

    // Save fields to quiz document
    quiz.score = score;
    quiz.totalMarks = totalMarks;
    quiz.percentage = percentage;
    quiz.userAnswers = new Map(Object.entries(userAnswers)); // Cast plain object to Map for Mongoose
    quiz.isSubmitted = true;
    quiz.submittedAt = new Date();

    await quiz.save();

    return res.status(200).json({
      success: true,
      message: "Quiz submitted successfully",
      result: {
        score,
        totalMarks,
        percentage,
        isSubmitted: quiz.isSubmitted,
        submittedAt: quiz.submittedAt,
      },
    });
  } catch (error) {
    console.error("Submit quiz error:", error);
    return res.status(500).json({
      success: false,
      message: error.message || "Server error submitting quiz results",
    });
  }
};

// Get all quizzes with pagination
const getQuizzes = async (req, res) => {
  try {
    const page = parseInt(req.query.page, 10) || 1;
    const limit = parseInt(req.query.limit, 10) || 10;
    const skip = (page - 1) * limit;

    const totalQuizzes = await Quiz.countDocuments({ user: req.user._id });

    const quizzes = await Quiz.find({ user: req.user._id })
      .select("-rawResponse -questions") // Keeps score, totalMarks, percentage, isSubmitted
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit);

    const totalPages = Math.ceil(totalQuizzes / limit);

    res.json({
      success: true,
      quizzes,
      pagination: {
        totalItems: totalQuizzes,
        totalPages,
        currentPage: page,
        pageSize: limit,
        hasNextPage: page < totalPages,
        hasPrevPage: page > 1,
      },
    });
  } catch (error) {
    console.error("Get quizzes error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching quizzes",
    });
  }
};

// Get single quiz with paginated questions
const getQuiz = async (req, res) => {
  try {
    const { id } = req.params;
    const page = parseInt(req.query.page, 10) || 1;
    const limit = parseInt(req.query.limit, 10) || 5; // Defaults to 5 questions per page

    const quiz = await Quiz.findOne({
      _id: id,
      user: req.user._id,
    }).select("-rawResponse");

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: "Quiz not found",
      });
    }

    const totalQuestions = quiz.questions.length;
    const totalPages = Math.ceil(totalQuestions / limit);
    const startIndex = (page - 1) * limit;
    const paginatedQuestions = quiz.questions.slice(startIndex, startIndex + limit);

    // Convert document to plain object so we can overwrite questions array
    const quizResponse = quiz.toObject();
    quizResponse.questions = paginatedQuestions;

    res.json({
      success: true,
      quiz: quizResponse,
      pagination: {
        totalQuestions,
        totalPages,
        currentPage: page,
        pageSize: limit,
        hasNextPage: page < totalPages,
        hasPrevPage: page > 1,
      },
    });
  } catch (error) {
    console.error("Get quiz error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching quiz",
    });
  }
};

// Delete quiz
const deleteQuiz = async (req, res) => {
  try {
    const { id } = req.params;

    const quiz = await Quiz.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: "Quiz not found",
      });
    }

    res.json({
      success: true,
      message: "Quiz deleted successfully",
    });
  } catch (error) {
    console.error("Delete quiz error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting quiz",
    });
  }
};

module.exports = { generateQuiz, submitQuiz, getQuizzes, getQuiz, deleteQuiz };