const Roadmap = require("../models/Roadmap");
const { ai, roadmapConfig } = require("../config/gemini");
const { callAIWithFallback } = require("../utils/aiWithFallback");

const buildPrompt = (goal) => `
  Generate a detailed learning roadmap for this goal:
  "${goal}"
  
  Make it specific, practical and chronological.
  Include real resources like MDN, freeCodeCamp, official docs.
  Break it down into phases with clear milestones.
`;

const generateRoadmap = async (req, res) => {
  try {
    const { goal } = req.body;

    if (!goal) {
      return res.status(400).json({
        success: false,
        message: "Please provide a goal",
      });
    }

    // AI Call
    const prompt = buildPrompt(goal);
    const response = await callAIWithFallback(ai, roadmapConfig, prompt);

    console.log(
      `Generated by: ${response.provider} on attempt: ${response.attempt}`
    );

    const parsedRoadmap = JSON.parse(response.text);

    const roadmap = await Roadmap.create({
      user: req.user._id,
      goal,
      title: parsedRoadmap.roadmapTitle || parsedRoadmap.title || goal,
      duration: parsedRoadmap.duration,
      phases: parsedRoadmap.phases,
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Roadmap generated successfully",
      roadmap,
    });
  } catch (error) {
    if (error.message && error.message.includes("All 5 attempts failed")) {
      return res.status(429).json({
        success: false,
        message: "Service temporarily unavailable. Please try again later.",
      });
    }
    console.error("Generate roadmap error:", error);
    res.status(500).json({
      success: false,
      message: "Server error generating roadmap",
    });
  }
};

const getRoadmaps = async (req, res) => {
  try {
    // Parse query params with fallback defaults
    let page = parseInt(req.query.page, 10);
    let limit = parseInt(req.query.limit, 10);

    // Sanitize input: ensure page >= 1 and limit is positive
    page = !isNaN(page) && page > 0 ? page : 1;
    limit = !isNaN(limit) && limit > 0 ? limit : 10;

    const skip = (page - 1) * limit;

    // Execute query and total count concurrently
    const [totalRoadmaps, roadmaps] = await Promise.all([
      Roadmap.countDocuments({ user: req.user._id }),
      Roadmap.find({ user: req.user._id })
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit),
    ]);

    const totalPages = Math.ceil(totalRoadmaps / limit) || 1;

    res.json({
      success: true,
      roadmaps,
      pagination: {
        totalRoadmaps,
        totalPages,
        currentPage: page,
        limit,
        hasNextPage: page < totalPages,
        hasPrevPage: page > 1,
      },
    });
  } catch (error) {
    console.error("Get roadmaps error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching roadmaps",
    });
  }
};

const deleteRoadmap = async (req, res) => {
  try {
    const { id } = req.params;

    const roadmap = await Roadmap.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!roadmap) {
      return res.status(404).json({
        success: false,
        message: "Roadmap not found or unauthorized",
      });
    }

    res.json({
      success: true,
      message: "Roadmap deleted successfully",
    });
  } catch (error) {
    console.error("Delete roadmap error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting roadmap",
    });
  }
};

module.exports = {
  generateRoadmap,
  getRoadmaps,
  deleteRoadmap,
};