const Roadmap = require("../models/Roadmap");
const { ai, roadmapConfig } = require("../config/gemini");
const { callAIWithFallback } = require("../utils/aiWithFallback");

const buildPrompt = (goal) => `
  Generate a detailed learning roadmap for this goal:
  "${goal}"
  
  Make it specific, practical and chronological.
  Include real resources like MDN, freeCodeCamp, official docs.
  Break it down into phases with clear milestones.
`;

// 1. জেনারেট নতুন রোডম্যাপ (সবসময় নতুন একটি Document তৈরি করবে)
const generateRoadmap = async (req, res) => {
  try {
    const { goal } = req.body;

    if (!goal) {
      return res.status(400).json({
        success: false,
        message: "Please provide a goal",
      });
    }

    // AI Call
    const prompt = buildPrompt(goal);
    const response = await callAIWithFallback(ai, roadmapConfig, prompt);

    console.log(
      `Generated by: ${response.provider} on attempt: ${response.attempt}`
    );

    const parsedRoadmap = JSON.parse(response.text);

    // সবসময় নতুন একটি Document ক্রিয়েট হবে
    const roadmap = await Roadmap.create({
      user: req.user._id,
      goal,
      title: parsedRoadmap.roadmapTitle || parsedRoadmap.title || goal,
      duration: parsedRoadmap.duration,
      phases: parsedRoadmap.phases,
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Roadmap generated successfully",
      roadmap,
    });
  } catch (error) {
    if (error.message && error.message.includes("All 5 attempts failed")) {
      return res.status(429).json({
        success: false,
        message: "Service temporarily unavailable. Please try again later.",
      });
    }
    console.error("Generate roadmap error:", error);
    res.status(500).json({
      success: false,
      message: "Server error generating roadmap",
    });
  }
};

// 2. ইউজারের সব রোডম্যাপের তালিকা ফেরত পাঠানো (find)
const getRoadmaps = async (req, res) => {
  try {
    // findOne এর বদলে find() ব্যবহার করা হয়েছে যাতে সব রোডম্যাপের array পাওয়া যায়
    const roadmaps = await Roadmap.find({ user: req.user._id }).sort({
      createdAt: -1,
    });

    res.json({
      success: true,
      roadmaps, // Array of roadmaps
    });
  } catch (error) {
    console.error("Get roadmaps error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching roadmaps",
    });
  }
};

// 3. নির্দিষ্ট একটি রোডম্যাপ ডিলিট করার রুট
const deleteRoadmap = async (req, res) => {
  try {
    const { id } = req.params;

    const roadmap = await Roadmap.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!roadmap) {
      return res.status(404).json({
        success: false,
        message: "Roadmap not found or unauthorized",
      });
    }

    res.json({
      success: true,
      message: "Roadmap deleted successfully",
    });
  } catch (error) {
    console.error("Delete roadmap error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting roadmap",
    });
  }
};

module.exports = {
  generateRoadmap,
  getRoadmaps,
  deleteRoadmap,
};