const StudyPlan = require("../models/StudyPlan");
const { ai, studyPlanConfig } = require("../config/gemini");
const { callAIWithFallback } = require('../utils/aiWithFallback');

const generateStudyPlan = async (req, res) => {
  try {
    const { currentLevel, subject } = req.body;

    if (!currentLevel || !subject) {
      return res.status(400).json({
        success: false,
        message: "Please provide currentLevel and subject",
      });
    }

    // Optimized prompt with strict JSON output schema and constraints
    const prompt = `
SYSTEM INSTRUCTION: You are an expert educational curriculum designer. Output ONLY valid JSON matching the exact schema specified below. Do NOT wrap the JSON in Markdown code fences (e.g. \`\`\`json) or include any introductory/concluding text.

TASK: Create a structured 7-day daily study plan.
- SUBJECT: ${subject}
- LEVEL: ${currentLevel}

REQUIREMENTS:
1. "planTitle": Short, high-impact, professional action title (e.g., "Mastering ${subject}", "Core ${subject} Blueprint").
   - Constraint: DO NOT include words like "7-Day", "7 Days", or "1-Week" in the title.
2. "summary": Concise 2-3 sentence overview of targeted learning outcomes.
3. "dailyPlan": An array of EXACTLY 7 items corresponding to Day 1 through Day 7.
   - Adjust task complexity to suit a student at the "${currentLevel}" level.
   - Each day must include specific, actionable tasks (2-4 items per day).
4. "tips": Array of 3 practical, actionable study/retention strategies tailored to ${subject}.

OUTPUT JSON SCHEMA:
{
  "planTitle": "string",
  "summary": "string",
  "dailyPlan": [
    {
      "day": 1,
      "topic": "string",
      "tasks": ["string", "string"]
    }
  ],
  "tips": ["string"]
}
`;

    const response = await callAIWithFallback(ai, studyPlanConfig, prompt);
    console.log(`Generated by: ${response.provider} on attempt: ${response.attempt}`);

    // Robust JSON Extraction (handles optional markdown blocks or trailing text safely)
    const jsonMatch = response.text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("Invalid response format received from AI model.");
    }

    const parsedPlan = JSON.parse(jsonMatch[0]);

    // Save to Database
    const studyPlan = await StudyPlan.create({
      user: req.user._id,
      currentLevel,
      subject,
      planTitle: parsedPlan.planTitle || `${subject} Study Plan`,
      summary: parsedPlan.summary || '',
      dailyPlan: parsedPlan.dailyPlan || [],
      weeklyTargets: parsedPlan.weeklyTargets || [],
      tips: parsedPlan.tips || [],
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Study plan generated successfully",
      studyPlan,
    });
  } catch (error) {
    if (error.message && error.message.includes('All 5 attempts failed')) {
      return res.status(429).json({
        success: false,
        message: 'Service temporarily unavailable. Please try again later.'
      });
    }
    console.error('Generate roadmap error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error generating roadmap'
    });
  }
};

// Get all study plans with Pagination
const getStudyPlans = async (req, res) => {
  try {
    const page = parseInt(req.query.page, 10) || 1;
    const limit = parseInt(req.query.limit, 10) || 10;
    const skip = (page - 1) * limit;

    const totalCount = await StudyPlan.countDocuments({ user: req.user._id });

    const studyPlans = await StudyPlan.find({ user: req.user._id })
      .select("-rawResponse")
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit);

    const totalPages = Math.ceil(totalCount / limit);

    res.json({
      success: true,
      count: studyPlans.length,
      pagination: {
        totalCount,
        totalPages,
        currentPage: page,
        limit,
        hasNextPage: page < totalPages,
        hasPrevPage: page > 1,
      },
      studyPlans,
    });
  } catch (error) {
    console.error("Get study plans error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching study plans",
    });
  }
};

// Get study plan by ID
const getStudyPlan = async (req, res) => {
  try {
    const { id } = req.params;

    const studyPlan = await StudyPlan.findOne({
      _id: id,
      user: req.user._id,
    });

    if (!studyPlan) {
      return res.status(404).json({
        success: false,
        message: "Study plan not found",
      });
    }

    res.json({
      success: true,
      studyPlan,
    });
  } catch (error) {
    console.error("Get study plan error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching study plan",
    });
  }
};

// Delete study plan
const deleteStudyPlan = async (req, res) => {
  try {
    const { id } = req.params;

    const studyPlan = await StudyPlan.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!studyPlan) {
      return res.status(404).json({
        success: false,
        message: "Study plan not found",
      });
    }

    res.json({
      success: true,
      message: "Study plan deleted successfully",
    });
  } catch (error) {
    console.error("Delete study plan error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting study plan",
    });
  }
};

module.exports = {
  generateStudyPlan,
  getStudyPlans,
  getStudyPlan,
  deleteStudyPlan,
};