// const StudyPlan = require("../models/StudyPlan");
// const { ai, studyPlanConfig } = require("../config/gemini");
// const { callAIWithFallback } = require('../utils/aiWithFallback');

// const generateStudyPlan = async (req, res) => {
//   try {
//     const { currentLevel, subject } = req.body;

//     if (!currentLevel || !subject) {
//       return res.status(400).json({
//         success: false,
//         message: "Please provide currentLevel and subject",
//       });
//     }

//     const prompt = `
//       Generate a detailed daily study plan with the following details:

//       Subject/Topic: ${subject}
//       Current Level: ${currentLevel}
      
//       Requirements:
//       - Create a realistic day by day study plan.
//       - Tips should be motivating and practical
//       - Tasks must match the ${currentLevel} level
//       - Be specific about what to study each day
//     `;

    

//     const response = await callAIWithFallback(ai, studyPlanConfig, prompt);
//     console.log(
//       `Generated by: ${response.provider} on attempt: ${response.attempt}`,
//     );
//     const parsedRoadmap = JSON.parse(response.text);

//     const parsedPlan = JSON.parse(response.text);

//     const studyPlan = await StudyPlan.create({
//       user: req.user._id,
//       currentLevel,
//       subject,
//       planTitle: parsedPlan.planTitle,
//       summary: parsedPlan.summary,
//       dailyPlan: parsedPlan.dailyPlan,
//       weeklyTargets: parsedPlan.weeklyTargets,
//       tips: parsedPlan.tips,
//       rawResponse: response.text,
//     });

//     res.status(201).json({
//       success: true,
//       message: "Study plan generated successfully",
//       studyPlan,
//     });
//   } catch (error) {
//     if (error.message.includes('All 5 attempts failed')) {
//       return res.status(429).json({
//         success: false,
//         message: 'Service temporarily unavailable. Please try again later.'
//       });
//     }
//     console.error('Generate roadmap error:', error);
//     res.status(500).json({
//       success: false,
//       message: 'Server error generating roadmap'
//     });
//   }
// };

// // get all study plans
// const getStudyPlans = async (req, res) => {
//   try {
//     const studyPlans = await StudyPlan.find({ user: req.user._id })
//       .select("-rawResponse")
//       .sort({ createdAt: -1 });

//     res.json({
//       success: true,
//       count: studyPlans.length,
//       studyPlans,
//     });
//   } catch (error) {
//     console.error("Get study plans error:", error);
//     res.status(500).json({
//       success: false,
//       message: "Server error fetching study plans",
//     });
//   }
// };

// // get study plan by id
// const getStudyPlan = async (req, res) => {
//   try {
//     const { id } = req.params;

//     const studyPlan = await StudyPlan.findOne({
//       _id: id,
//       user: req.user._id,
//     });

//     if (!studyPlan) {
//       return res.status(404).json({
//         success: false,
//         message: "Study plan not found",
//       });
//     }

//     res.json({
//       success: true,
//       studyPlan,
//     });
//   } catch (error) {
//     console.error("Get study plan error:", error);
//     res.status(500).json({
//       success: false,
//       message: "Server error fetching study plan",
//     });
//   }
// };

// // delete
// const deleteStudyPlan = async (req, res) => {
//   try {
//     const { id } = req.params;

//     const studyPlan = await StudyPlan.findOneAndDelete({
//       _id: id,
//       user: req.user._id,
//     });

//     if (!studyPlan) {
//       return res.status(404).json({
//         success: false,
//         message: "Study plan not found",
//       });
//     }

//     res.json({
//       success: true,
//       message: "Study plan deleted successfully",
//     });
//   } catch (error) {
//     console.error("Delete study plan error:", error);
//     res.status(500).json({
//       success: false,
//       message: "Server error deleting study plan",
//     });
//   }
// };



// module.exports = {
//   generateStudyPlan,
//   getStudyPlans,
//   getStudyPlan,
//   deleteStudyPlan,
// };

const StudyPlan = require("../models/StudyPlan");
const { ai, studyPlanConfig } = require("../config/gemini");
const { callAIWithFallback } = require('../utils/aiWithFallback');

const generateStudyPlan = async (req, res) => {
  try {
    const { currentLevel, subject } = req.body;

    if (!currentLevel || !subject) {
      return res.status(400).json({
        success: false,
        message: "Please provide currentLevel and subject",
      });
    }

    // 🎯 Prompt updated with EXACT JSON Schema requirements for Groq & Gemini
// const prompt = `
//       Generate a detailed daily study plan for:
//       Subject/Topic: ${subject}
//       Current Level: ${currentLevel}
      
//       Requirements:
//       - Create a realistic day-by-day study plan.
//       - Tips should be motivating and practical.
//       - Tasks must match the ${currentLevel} level.
//       - Be specific about what to study each day.

//       You MUST respond strictly with a JSON object following this exact format:
//       {
//         "planTitle": "Title of the study plan",
//         "summary": "Short overview/summary",
//         "dailyPlan": [
//           {
//             "day": 1,
//             "topic": "Topic Name",
//             "tasks": ["Task 1", "Task 2"]
//           }
//         ],
//         "weeklyTargets": [
//           {
//             "week": 1,
//             "target": "Target description for week 1"
//           }
//         ],
//         "tips": ["Tip 1", "Tip 2"]
//       }
//     `;

const prompt = `
      Create a focused 7-day daily study plan for:
      Subject: ${subject}
      Level: ${currentLevel}

      STRICT RULES:
      - "planTitle" MUST be dynamic, engaging, and professional (e.g., "Mastering ${subject}", "${subject} Core Blueprint", "Accelerated ${subject} Learning Path").
      - DO NOT include terms like "7-Day", "7 Days", or "1-Week" in the "planTitle". Keep the title clean.
      - "dailyPlan" MUST contain EXACTLY 7 items (Day 1 through Day 7).
      - Do NOT include any weekly targets or week-based groups. Just focus on Day 1 to Day 7.

      Respond STRICTLY with a JSON object following this format:
      {
        "planTitle": "Professional Action-Oriented Title Without Days Included",
        "summary": "Short summary of what will be learned in this 7-day plan",
        "dailyPlan": [
          {
            "day": 1,
            "topic": "Day 1 Topic",
            "tasks": ["Task 1", "Task 2"]
          },
          {
            "day": 2,
            "topic": "Day 2 Topic",
            "tasks": ["Task 1", "Task 2"]
          },
          {
            "day": 3,
            "topic": "Day 3 Topic",
            "tasks": ["Task 1", "Task 2"]
          },
          {
            "day": 4,
            "topic": "Day 4 Topic",
            "tasks": ["Task 1", "Task 2"]
          },
          {
            "day": 5,
            "topic": "Day 5 Topic",
            "tasks": ["Task 1", "Task 2"]
          },
          {
            "day": 6,
            "topic": "Day 6 Topic",
            "tasks": ["Task 1", "Task 2"]
          },
          {
            "day": 7,
            "topic": "Day 7 Topic",
            "tasks": ["Task 1", "Task 2"]
          }
        ],
        "tips": ["Tip 1", "Tip 2"]
      }
    `;

    const response = await callAIWithFallback(ai, studyPlanConfig, prompt);
    console.log(
      `Generated by: ${response.provider} on attempt: ${response.attempt}`,
    );

    // Clean response text if LLM includes markdown code blocks
    const cleanText = response.text.replace(/```json/g, '').replace(/```/g, '').trim();
    const parsedPlan = JSON.parse(cleanText);

    // Save to Mongo DB
    const studyPlan = await StudyPlan.create({
      user: req.user._id,
      currentLevel,
      subject,
      planTitle: parsedPlan.planTitle || `${subject} Study Plan`,
      summary: parsedPlan.summary || '',
      dailyPlan: parsedPlan.dailyPlan || [],
      weeklyTargets: parsedPlan.weeklyTargets || [],
      tips: parsedPlan.tips || [],
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Study plan generated successfully",
      studyPlan,
    });
  } catch (error) {
    if (error.message.includes('All 5 attempts failed')) {
      return res.status(429).json({
        success: false,
        message: 'Service temporarily unavailable. Please try again later.'
      });
    }
    console.error('Generate roadmap error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error generating roadmap'
    });
  }
};

// get all study plans
const getStudyPlans = async (req, res) => {
  try {
    const studyPlans = await StudyPlan.find({ user: req.user._id })
      .select("-rawResponse")
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      count: studyPlans.length,
      studyPlans,
    });
  } catch (error) {
    console.error("Get study plans error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching study plans",
    });
  }
};

// get study plan by id
const getStudyPlan = async (req, res) => {
  try {
    const { id } = req.params;

    const studyPlan = await StudyPlan.findOne({
      _id: id,
      user: req.user._id,
    });

    if (!studyPlan) {
      return res.status(404).json({
        success: false,
        message: "Study plan not found",
      });
    }

    res.json({
      success: true,
      studyPlan,
    });
  } catch (error) {
    console.error("Get study plan error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching study plan",
    });
  }
};

// delete
const deleteStudyPlan = async (req, res) => {
  try {
    const { id } = req.params;

    const studyPlan = await StudyPlan.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!studyPlan) {
      return res.status(404).json({
        success: false,
        message: "Study plan not found",
      });
    }

    res.json({
      success: true,
      message: "Study plan deleted successfully",
    });
  } catch (error) {
    console.error("Delete study plan error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting study plan",
    });
  }
};

module.exports = {
  generateStudyPlan,
  getStudyPlans,
  getStudyPlan,
  deleteStudyPlan,
};