const StudyPlan = require("../models/StudyPlan");
const { ai, studyPlanConfig } = require("../config/gemini");
const callAIWithFallback = require("../utils/aiWithFallback");

const generateStudyPlan = async (req, res) => {
  try {
    const { currentLevel, subject } = req.body;

    if (!currentLevel || !subject) {
      return res.status(400).json({
        success: false,
        message: "Please provide currentLevel and subject",
      });
    }

    const prompt = `
      Generate a detailed daily study plan with the following details:

      Subject/Topic: ${subject}
      Current Level: ${currentLevel}
      
      Requirements:
      - Create a realistic day by day study plan.
      - Tips should be motivating and practical
      - Tasks must match the ${currentLevel} level
      - Be specific about what to study each day
    `;

    

    const response = await callAIWithFallback(ai, roadmapConfig, prompt);
    console.log(
      `Generated by: ${response.provider} on attempt: ${response.attempt}`,
    );
    const parsedRoadmap = JSON.parse(response.text);

    const parsedPlan = JSON.parse(response.text);

    const studyPlan = await StudyPlan.create({
      user: req.user._id,
      currentLevel,
      subject,
      planTitle: parsedPlan.planTitle,
      summary: parsedPlan.summary,
      dailyPlan: parsedPlan.dailyPlan,
      weeklyTargets: parsedPlan.weeklyTargets,
      tips: parsedPlan.tips,
      rawResponse: response.text,
    });

    res.status(201).json({
      success: true,
      message: "Study plan generated successfully",
      studyPlan,
    });
  } catch (error) {
    if (error.message.includes('All 5 attempts failed')) {
      return res.status(429).json({
        success: false,
        message: 'Service temporarily unavailable. Please try again later.'
      });
    }
    console.error('Generate roadmap error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error generating roadmap'
    });
  }
};

// get all study plans
const getStudyPlans = async (req, res) => {
  try {
    const studyPlans = await StudyPlan.find({ user: req.user._id })
      .select("-rawResponse")
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      count: studyPlans.length,
      studyPlans,
    });
  } catch (error) {
    console.error("Get study plans error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching study plans",
    });
  }
};

// get study plan by id
const getStudyPlan = async (req, res) => {
  try {
    const { id } = req.params;

    const studyPlan = await StudyPlan.findOne({
      _id: id,
      user: req.user._id,
    });

    if (!studyPlan) {
      return res.status(404).json({
        success: false,
        message: "Study plan not found",
      });
    }

    res.json({
      success: true,
      studyPlan,
    });
  } catch (error) {
    console.error("Get study plan error:", error);
    res.status(500).json({
      success: false,
      message: "Server error fetching study plan",
    });
  }
};

// delete
const deleteStudyPlan = async (req, res) => {
  try {
    const { id } = req.params;

    const studyPlan = await StudyPlan.findOneAndDelete({
      _id: id,
      user: req.user._id,
    });

    if (!studyPlan) {
      return res.status(404).json({
        success: false,
        message: "Study plan not found",
      });
    }

    res.json({
      success: true,
      message: "Study plan deleted successfully",
    });
  } catch (error) {
    console.error("Delete study plan error:", error);
    res.status(500).json({
      success: false,
      message: "Server error deleting study plan",
    });
  }
};

module.exports = {
  generateStudyPlan,
  getStudyPlans,
  getStudyPlan,
  deleteStudyPlan,
};
