const WellnessLog = require('../models/WellnessLog');
const User = require('../models/User');
const Todo = require('../models/Todo'); 
const { isValidDateString } = require('../utils/dateHelper');
const { calculateEnergyScore } = require('../utils/energyScoreEngine');

const { ai, weeklyReportConfig } = require('../config/gemini');
const { callAIWithFallback } = require('../utils/aiWithFallback');


const updateEnergyScore = async (userId, date) => {
  const log = await WellnessLog.findOne({ user: userId, date });
  if (log) {
    const newScore = calculateEnergyScore(log);
    log.energyScore = newScore;
    await log.save();
    return log;
  }
  return null;
};

const evaluateBurnoutRisk = async (userId) => {
  const today = new Date();
  const past3Days = new Date(today);
  past3Days.setDate(past3Days.getDate() - 3);

  const formatDate = (dateObj) => {
    const tzOffset = dateObj.getTimezoneOffset() * 60000;
    return new Date(dateObj.getTime() - tzOffset).toISOString().split('T')[0];
  };

  const logs = await WellnessLog.find({
    user: userId,
    date: { $gte: formatDate(past3Days) }
  }).sort({ date: -1 });

  if (logs.length < 3) return { isBurnout: false, reason: 'Insufficient data' };

  // Rule 1: 3 consecutive days with energy score < 50
  const consecutiveLowScores = logs.every(log => (log.energyScore || 50) < 50);

  // Rule 2: Low sleep (< 6 hrs) + High screen time (> 300 mins) on recent days
  const badHabitPattern = logs.some(log => 
    (log.sleep?.hours && log.sleep.hours < 6) && 
    (log.screenTime?.usedMinutes && log.screenTime.usedMinutes > 300)
  );

  if (consecutiveLowScores) {
    return {
      isBurnout: true,
      reason: 'Your Energy Score has been consistently below 50 for the past 3 days.'
    };
  }

  if (badHabitPattern) {
    return {
      isBurnout: true,
      reason: 'Detected a pattern of low sleep combined with high screen time.'
    };
  }

  return { isBurnout: false };
};

// GET /api/wellness/weekly-report
const generateWeeklyReport = async (req, res) => {
  try {
    const today = new Date();
    const pastWeek = new Date(today);
    pastWeek.setDate(pastWeek.getDate() - 6);

    const formatDate = (dateObj) => {
      const tzOffset = dateObj.getTimezoneOffset() * 60000;
      return new Date(dateObj.getTime() - tzOffset).toISOString().split('T')[0];
    };

    const fromDate = formatDate(pastWeek);
    const toDate = formatDate(today);

    // 1. Fetch Real Wellness Logs for the 7-day window
    const wellnessLogs = await WellnessLog.find({
      user: req.user._id,
      date: { $gte: fromDate, $lte: toDate }
    });

    if (!wellnessLogs || wellnessLogs.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'No wellness logs found for the past 7 days. Please log your data first.'
      });
    }

    // 2. Fetch Real Productivity (Todo) Data
    const todos = await Todo.find({
      user: req.user._id,
      createdAt: { $gte: pastWeek, $lte: today }
    });

    // 3. Aggregate Statistical Metrics
    let totalEnergy = 0;
    let totalScreenTime = 0;
    let totalSleep = 0;
    let totalWater = 0;

    wellnessLogs.forEach((log) => {
      totalEnergy += log.energyScore || 0;
      totalScreenTime += log.screenTime?.usedMinutes || 0;
      totalSleep += log.sleep?.hours || 0;
      totalWater += log.water?.consumedMl || 0;
    });

    const daysLogged = wellnessLogs.length;
    const avgEnergy = Math.round(totalEnergy / daysLogged);
    const avgScreenTime = Math.round(totalScreenTime / daysLogged);
    const avgSleep = (totalSleep / daysLogged).toFixed(1);
    const avgWater = Math.round(totalWater / daysLogged);

    const totalTasks = todos.length;
    const completedTasks = todos.filter((t) => t.status === 'completed' || t.isCompleted).length;
    const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

    // 4. Construct Prompt with Explicit Real Numbers
    const prompt = `
      Analyze the following 7-day health and productivity summary for the user:

      - Days Logged: ${daysLogged} / 7 days
      - Average Energy Score: ${avgEnergy} / 100
      - Average Sleep: ${avgSleep} hours/night
      - Average Daily Screen Time: ${avgScreenTime} minutes
      - Average Water Intake: ${avgWater} ml/day
      - Tasks Completed: ${completedTasks} / ${totalTasks} (${completionRate}% completion rate)

      Correlate how sleep, screen time, and hydration impacted the user's task completion efficiency.
      Evaluate burnout risk and return the analysis strictly adhering to the JSON schema.
    `;

    // 5. Run with Gemini -> Groq Fallback Engine
    const response = await callAIWithFallback(ai, weeklyReportConfig, prompt);
    console.log(`[WEEKLY REPORT] Generated by: ${response.provider} on attempt: ${response.attempt}`);

    const parsedReport = JSON.parse(response.text);

    return res.status(200).json({
      success: true,
      message: 'Weekly AI report generated successfully',
      data: {
        ...parsedReport,
        stats: {
          daysLogged,
          avgEnergy,
          avgSleep,
          avgScreenTime,
          avgWater,
          completedTasks,
          totalTasks,
          completionRate
        }
      }
    });

  } catch (error) {
    if (error.message.includes('All 5 attempts failed')) {
      return res.status(429).json({
        success: false,
        message: 'AI engine is currently busy. Please try again in a few moments.'
      });
    }
    console.error('Weekly Report Generation Error:', error);
    return res.status(500).json({
      success: false,
      message: 'Server error generating weekly report',
      error: error.message
    });
  }
};

// POST /api/wellness/water-settings
const updateWaterSettings = async (req, res) => {
  try {
    const { timezone, isActive, targetMl, wakeTime, sleepTime, intervalHours, isEmailAlertEnabled } = req.body;

    const updateFields = {};
    if (timezone) updateFields.timezone = timezone;
    
    if (isActive !== undefined || targetMl !== undefined || wakeTime || sleepTime || intervalHours || isEmailAlertEnabled !== undefined) {
      updateFields.waterSettings = {};
      
      const user = await User.findById(req.user._id);
      const currentSettings = user.waterSettings || {};

      updateFields.waterSettings.isActive = isActive !== undefined ? isActive : currentSettings.isActive;
      updateFields.waterSettings.targetMl = targetMl !== undefined ? targetMl : currentSettings.targetMl;
      updateFields.waterSettings.wakeTime = wakeTime || currentSettings.wakeTime;
      updateFields.waterSettings.sleepTime = sleepTime || currentSettings.sleepTime;
      updateFields.waterSettings.intervalHours = intervalHours || currentSettings.intervalHours;
      updateFields.waterSettings.isEmailAlertEnabled = isEmailAlertEnabled !== undefined ? isEmailAlertEnabled : currentSettings.isEmailAlertEnabled;
    }

    const updatedUser = await User.findByIdAndUpdate(
      req.user._id,
      { $set: updateFields },
      { new: true, runValidators: true }
    ).select('-password');

    return res.status(200).json({
      success: true,
      message: 'Settings updated successfully',
      data: updatedUser
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: 'Failed to update settings',
      error: error.message
    });
  }
};

// GET /api/wellness/logs/:date
const getLogByDate = async (req, res) => {
  try {
    const { date } = req.params;

    if (!isValidDateString(date)) {
      return res.status(400).json({ success: false, message: 'Invalid date format' });
    }

    const log = await WellnessLog.findOne({ user: req.user._id, date });

    return res.status(200).json({
      success: true,
      message: log ? 'Log found' : 'No log for this date yet',
      data: log || null
    });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to fetch wellness log', error: error.message });
  }
};

// GET /api/wellness/logs?from=YYYY-MM-DD&to=YYYY-MM-DD
const getLogsInRange = async (req, res) => {
  try {
    const { from, to } = req.query;

    if (!isValidDateString(from) || !isValidDateString(to)) {
      return res.status(400).json({ success: false, message: 'Invalid from/to date' });
    }

    const logs = await WellnessLog.find({
      user: req.user._id,
      date: { $gte: from, $lte: to }
    }).sort({ date: 1 });

    return res.status(200).json({ success: true, message: `${logs.length} log(s) found`, data: logs });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to fetch logs', error: error.message });
  }
};

// POST /api/wellness/water
const addWaterEntry = async (req, res) => {
  try {
    const { date, amountMl } = req.body;

    if (!isValidDateString(date)) {
      return res.status(400).json({ success: false, message: 'Invalid date format' });
    }

    if (typeof amountMl !== 'number' || amountMl <= 0) {
      return res.status(400).json({ success: false, message: 'amountMl must be positive' });
    }

    const user = await User.findById(req.user._id);
    const targetMl = user?.waterSettings?.targetMl || 2000;

    await WellnessLog.findOneAndUpdate(
      { user: req.user._id, date },
      {
        $inc: { 'water.consumedMl': amountMl },
        $push: { 'water.entries': { amountMl, loggedAt: new Date() } },
        $setOnInsert: { user: req.user._id, date, 'water.targetMl': targetMl }
      },
      { upsert: true, new: true }
    );

    const updatedLog = await updateEnergyScore(req.user._id, date);

    return res.status(200).json({ success: true, message: 'Water entry added', data: updatedLog });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to add water', error: error.message });
  }
};

// GET /api/wellness/water-settings
const getWaterSettings = async (req, res) => {
  try {
    const user = await User.findById(req.user._id).select('waterSettings timezone');
    
    return res.status(200).json({
      success: true,
      data: {
        timezone: user.timezone,
        waterSettings: user.waterSettings || {
          isActive: false,
          targetMl: 2000,
          wakeTime: '08:00',
          sleepTime: '22:00',
          intervalHours: 2,
          isEmailAlertEnabled: false
        }
      }
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch water settings',
      error: error.message
    });
  }
};

// PATCH /api/wellness/screen-time
const updateScreenTime = async (req, res) => {
  try {
    const { date, usedMinutes, limitMinutes } = req.body;

    if (!isValidDateString(date)) return res.status(400).json({ success: false, message: 'Invalid date' });

    const update = { $setOnInsert: { user: req.user._id, date } };
    const set = {};
    if (usedMinutes !== undefined) set['screenTime.usedMinutes'] = usedMinutes;
    if (limitMinutes !== undefined) set['screenTime.limitMinutes'] = limitMinutes;
    if (Object.keys(set).length) update.$set = set;

    await WellnessLog.findOneAndUpdate({ user: req.user._id, date }, update, { upsert: true, new: true });
    
    const updatedLog = await updateEnergyScore(req.user._id, date);

    return res.status(200).json({ success: true, message: 'Screen time updated', data: updatedLog });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to update screen time', error: error.message });
  }
};

// PATCH /api/wellness/sleep
const updateSleep = async (req, res) => {
  try {
    const { date, hours, quality } = req.body;

    if (!isValidDateString(date)) return res.status(400).json({ success: false, message: 'Invalid date' });

    // Ensure hours is explicitly parsed as a Number
    const parsedHours = hours !== undefined ? Number(hours) : undefined;

    const set = { $setOnInsert: { user: req.user._id, date } };
    if (parsedHours !== undefined) set['sleep.hours'] = parsedHours;
    if (quality !== undefined) set['sleep.quality'] = quality;

    await WellnessLog.findOneAndUpdate(
      { user: req.user._id, date },
      { $set: set, $setOnInsert: { user: req.user._id, date } },
      { upsert: true, new: true }
    );
    
    const updatedLog = await updateEnergyScore(req.user._id, date);

    return res.status(200).json({ success: true, message: 'Sleep log updated', data: updatedLog });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to update sleep', error: error.message });
  }
};

// PATCH /api/wellness/mood
const updateMood = async (req, res) => {
  try {
    const { date, value, note } = req.body;

    if (!isValidDateString(date)) return res.status(400).json({ success: false, message: 'Invalid date' });
    if (value !== undefined && (value < 1 || value > 5)) return res.status(400).json({ success: false, message: 'Mood 1-5' });

    const set = {};
    if (value !== undefined) set['mood.value'] = value;
    if (note !== undefined) set['mood.note'] = note;

    await WellnessLog.findOneAndUpdate(
      { user: req.user._id, date },
      { $set: set, $setOnInsert: { user: req.user._id, date } },
      { upsert: true, new: true }
    );
    
    const updatedLog = await updateEnergyScore(req.user._id, date);

    return res.status(200).json({ success: true, message: 'Mood updated', data: updatedLog });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to update mood', error: error.message });
  }
};

// PATCH /api/wellness/activity
const updateActivity = async (req, res) => {
  try {
    const { date, type, minutes } = req.body;

    if (!isValidDateString(date)) return res.status(400).json({ success: false, message: 'Invalid date' });

    const set = {};
    if (type !== undefined) set['activity.type'] = type;
    if (minutes !== undefined) set['activity.minutes'] = minutes;

    await WellnessLog.findOneAndUpdate(
      { user: req.user._id, date },
      { $set: set, $setOnInsert: { user: req.user._id, date } },
      { upsert: true, new: true }
    );
    
    const updatedLog = await updateEnergyScore(req.user._id, date);

    return res.status(200).json({ success: true, message: 'Activity logged', data: updatedLog });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to log activity', error: error.message });
  }
};

module.exports = {
  updateWaterSettings,
  getWaterSettings,
  getLogByDate,
  getLogsInRange,
  addWaterEntry,
  updateScreenTime,
  updateSleep,
  updateMood,
  updateActivity,
  generateWeeklyReport
};